apiVersion: v1
kind: Service
metadata:
  name: rsocket-ping
  labels:
    app: rsocket-ping
    service: rsocket-ping
spec:
  type: NodePort
  ports:
  - name: rsocket-ping
    port: 8080
    targetPort: 8080
  selector:
    app: rsocket-ping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsocket-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsocket-ping
      version: v0.0.1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: rsocket-ping
        version: v0.0.1
    spec:
      containers:
      - image: ssingh3339/rsocket-ping:latest
        imagePullPolicy: Always
        name: rsocket-ping
        ports:
        - containerPort: 8080
        env:
        - name: TLS
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        - name: ADDRESS
          value: ":8080"
        resources:
            limits:
              cpu: ".25"
              memory: 100Mi
            requests:
              cpu: ".10"
              memory: 50Mi
