apiVersion: v1
kind: Service
metadata:
  name: graphql-rest
  labels:
    app: graphql-rest
    service: graphql-rest
spec:
  type: NodePort
  ports:
  - name: http-graphql-rest
    port: 8080
    targetPort: 8080
  selector:
    app: graphql-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-rest
      version: v0.0.1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: graphql-rest
        version: v0.0.1
    spec:
      containers:
      - image: ssingh3339/graphql-rest:latest
        imagePullPolicy: Always
        name: graphql-rest
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: ".5"
              memory: 100Mi
            requests:
              cpu: ".25"
              memory: 50Mi
