apiVersion: v1
kind: Service
metadata:
  name: echo-graphql
  labels:
    app: echo-graphql
    service: echo-graphql
spec:
  type: NodePort
  ports:
  - name: echo-graphql
    port: 8080
    targetPort: 8080
  selector:
    app: echo-graphql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-graphql
      version: v0.0.1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: echo-graphql
        version: v0.0.1
    spec:
      containers:
      - image: ssingh3339/echo-graphql:latest
        imagePullPolicy: Always
        name: echo-graphql
        ports:
        - containerPort: 8080
        env:
        - name: TLS
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        - name: ADDRESS
          value: ":8080"
        resources:
            limits:
              cpu: ".25"
              memory: 100Mi
            requests:
              cpu: ".10"
              memory: 50Mi
